a=float(input("Enter a number to do various operations:"))
b=float(input("Enter the other number for perfoming various operations:"))
print("The sum is",a+b)
print("The differnce is",a-b)
print("The product is",a*b)
print("The quotient is",a/b)
print("The remainder is",a%b)
print("The power is",a**b)
print("The floor value is",a//b)
print("a>b is", a>b)
print("a<b is", a<b)
print("a!=b is", a!=b)
print("a==b is", a==b)
print("a>=b is", a>=b)
print("a<=b is", a<=b)
print("The increment of a is ",a+1)
print("The decrement of b is",b-1)


